// Tüm etkinlik verisi tek yerde. Sayfalar kartları, detayı ve formu bu diziden üretir.
// Tarih: YYYY-AA-GG (sıralama ve <input type="date"> için), saat: SS:DD.
export const events = [
  {
    id: "event-1",
    title: "Kariyer Günleri 2026",
    category: "Seminer",
    date: "2026-10-12",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    description: "Mezunlarla kariyer söyleşileri ve şirket standları.",
    capacity: 120,
  },
  {
    id: "event-2",
    title: "Robotik Atölyesi",
    category: "Atölye",
    date: "2026-10-20",
    time: "10:00",
    location: "Bilgisayar Laboratuvarı 2",
    description: "Robotik ve kodlama atölyesinde uygulamalı çalışmalar yapılacak.",
    capacity: 30,
  },
  {
    id: "event-3",
    title: "Siber Güvenlik Söyleşisi",
    category: "Söyleşi",
    date: "2026-10-27",
    time: "13:00",
    location: "B Blok Amfi 1",
    description: "Sektörden bir uzmanla güvenlik kariyeri üzerine sohbet.",
    capacity: 50,
  },
  {
    id: "event-4",
    title: "Web Tasarım Atölyesi",
    category: "Atölye",
    date: "2026-11-03",
    time: "15:00",
    location: "Bilgisayar Laboratuvarı 1",
    description: "HTML ve CSS ile ilk kişisel sayfanı hazırla.",
    capacity: 30,
  },
  {
    id: "event-5",
    title: "Yapay Zekâ Semineri",
    category: "Seminer",
    date: "2026-11-10",
    time: "11:00",
    location: "C Blok Amfi",
    description: "Yapay zekânın günlük hayata ve mesleklere etkisi konuşulacak.",
    capacity: 150,
  },
  {
    id: "event-6",
    title: "Yeni Öğrenci Oryantasyonu",
    category: "Oryantasyon",
    date: "2026-11-17",
    time: "10:00",
    location: "Merkez Amfi",
    description: "Yeni öğrencilere kampüs, bölüm ve öğrenci toplulukları tanıtılacak.",
    capacity: 200,
  },
];
